"""MCQ generation route — produces quiz questions from slide content.

Returns 5 multiple-choice questions, each with 4 options (A-D) and
the correct answer letter, all generated by qwen2:1.5b via Ollama.

Performance: Uses only top-5 relevant chunks (not entire document)
for much faster generation (<10s typical).
"""

from __future__ import annotations

import json
import logging
import re
from typing import Optional

from fastapi import APIRouter, Request, HTTPException
from pydantic import BaseModel, Field

from app.services.prompt_templates import build_mcq_prompt

logger = logging.getLogger(__name__)

router = APIRouter()


# ── Request / Response models ───────────────────────────────

class MCQRequest(BaseModel):
    document_id: str


class MCQOption(BaseModel):
    label: str = Field(..., description="Option letter (A, B, C, D)")
    text: str = Field(..., description="Option text")


class MCQQuestion(BaseModel):
    question_number: int
    question: str
    options: list[MCQOption]
    correct_answer: str = Field(..., description="Correct option letter (A / B / C / D)")


class MCQResponse(BaseModel):
    questions: list[MCQQuestion]
    model: str
    chunks_used: int
    eval_tokens: Optional[int] = None
    eval_duration_ms: Optional[float] = None


# ── Helpers ─────────────────────────────────────────────────

_JSON_BLOCK_RE = re.compile(r"```(?:json)?\s*([\s\S]*?)```")


def _extract_json(text: str) -> list[dict]:
    """
    Parse the LLM response into a list of MCQ dicts.

    Handles:
      - Raw JSON arrays
      - JSON wrapped in markdown code fences
      - Minor trailing-comma issues
    """
    # Try raw parse first
    cleaned = text.strip()
    try:
        data = json.loads(cleaned)
        if isinstance(data, list):
            return data
    except json.JSONDecodeError:
        pass

    # Try extracting from markdown fences
    m = _JSON_BLOCK_RE.search(cleaned)
    if m:
        try:
            data = json.loads(m.group(1).strip())
            if isinstance(data, list):
                return data
        except json.JSONDecodeError:
            pass

    # Last attempt — find the first '[' and last ']'
    start = cleaned.find("[")
    end = cleaned.rfind("]")
    if start != -1 and end != -1 and end > start:
        try:
            data = json.loads(cleaned[start : end + 1])
            if isinstance(data, list):
                return data
        except json.JSONDecodeError:
            pass

    return []


def _normalise_questions(raw: list[dict]) -> list[MCQQuestion]:
    """
    Convert raw LLM JSON into validated ``MCQQuestion`` objects.

    Tolerates small variations in key names and option formats.
    """
    questions: list[MCQQuestion] = []

    for idx, item in enumerate(raw[:5], start=1):
        q_text = item.get("question", "").strip()
        if not q_text:
            continue

        # Parse options — accept both list-of-strings and list-of-dicts
        raw_options = item.get("options", [])
        options: list[MCQOption] = []

        for i, opt in enumerate(raw_options[:4]):
            letter = chr(65 + i)  # A, B, C, D

            if isinstance(opt, dict):
                opt_text = opt.get("text", opt.get("label", str(opt)))
            else:
                opt_text = str(opt)

            # Strip leading label if model included it (e.g. "A. Newton")
            opt_text = re.sub(r"^[A-Da-d][.)]\s*", "", opt_text).strip()
            options.append(MCQOption(label=letter, text=opt_text))

        # Pad to 4 if model returned fewer
        while len(options) < 4:
            options.append(MCQOption(label=chr(65 + len(options)), text="N/A"))

        correct = item.get("correct_answer", item.get("answer", "A"))
        correct = str(correct).strip().upper()[:1]
        if correct not in {"A", "B", "C", "D"}:
            correct = "A"

        questions.append(
            MCQQuestion(
                question_number=idx,
                question=q_text,
                options=options,
                correct_answer=correct,
            )
        )

    return questions


# ── Endpoint ────────────────────────────────────────────────

@router.post("/generate-mcq", response_model=MCQResponse)
async def generate_mcq(request: Request, body: MCQRequest):
    """
    Generate 5 multiple-choice questions from the slide content of a
    processed document.

    Each question has 4 options (A-D) with the correct answer marked.
    """
    embedding_service = request.app.state.embedding_service
    ollama_service = request.app.state.ollama_service

    # Focused retrieval — top 5 relevant chunks for faster generation
    results = embedding_service.search(
        body.document_id,
        "key concepts definitions facts important details examples",
        top_k=5,
    )

    if not results:
        raise HTTPException(
            status_code=404,
            detail="No content found for this document. Has it been processed?",
        )

    # Build prompt — keep compact for speed
    prompt = build_mcq_prompt(results)

    # Cap prompt length to keep generation fast
    if len(prompt) > 3000:
        prompt = prompt[:3000] + "\n\n[Content truncated]"

    # Use low temperature for deterministic, well-formatted JSON output
    result = await ollama_service.generate(
        prompt,
        temperature=0.2,
        max_tokens=1200,
    )

    if not result.ok:
        raise HTTPException(status_code=503, detail=result.content)

    # Parse & validate JSON from LLM
    raw_questions = _extract_json(result.content)

    if not raw_questions:
        logger.warning("MCQ generation returned unparseable output: %s", result.content[:300])
        raise HTTPException(
            status_code=502,
            detail="The AI model did not return valid MCQ JSON. Please try again.",
        )

    questions = _normalise_questions(raw_questions)

    if not questions:
        raise HTTPException(
            status_code=502,
            detail="Could not parse any valid questions from the AI response.",
        )

    return MCQResponse(
        questions=questions,
        model=result.model,
        chunks_used=len(results),
        eval_tokens=result.eval_count,
        eval_duration_ms=result.eval_duration_ms,
    )
